version: "3"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - /var/databases/mongodb/ecommerce:/db
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: api
    image: fastapi-ecommerce
    restart: always
    ports:
      - "8888:8888"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/
    depends_on:
      - mongodb